---
# ==============================================================================
# Emplacement : /projets_optimedit/infra_iis_ansible/infra_iis_cert_wc_ansible_v.2.14.18/roles/adcs_setup\tasks
# Fichier      : /adcs_setup/tasks/main.yml
# ==============================================================================
# Tasks for adcs_setup
