---
# ==============================================================================
# Emplacement : /projets_optimedit/iis_infras/infra_iis_cert_wc_ansible_v.2.14.18/group_vars/
# Fichier : srv_adcs_vault.yml
# ==============================================================================