---
# ==============================================================================
# Emplacement : /projets_optimedit/infra_iis_ansible/infra_iis_cert_wc_ansible_v.2.14.18/roles/fs_setup\tasks
# Fichier      : /fs_setup/tasks/main.yml
# ==============================================================================
# Tasks for fs_setup

